home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('base/',views.base, name='base'),
    path('others/', views.others, name='others'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

mkt/urls.py
from django.urls import path, include
from django.contrib import admin
from home import views


urlpatterns = [
    
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')

]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)


    profile_portfolio = models.URLField(blank=True)


    profile_pic = models.ImageField(upload_to = 'profile_pic', blank=True)

    def __str__(self):
        return self.user.username
        

home/forms.py
from django import forms
from django.contrib.auth.models import User
from home.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():

        model = User
        fields = {'username', 'password','email'}

class UserProfileInfoForm(forms.ModelForm):

    class Meta():

        model = UserProfileInfo
        fields = {'profile_portfolio', 'profile_pic'}

        

home/views.py
from django.shortcuts import render
from home.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required



def index(request):
    context_dic = {'name':'mera nam jo bhi ap apne kaam sde', 'age':'31'}
    return render(request, 'home/index.html',context=context_dic)

def base(request):
    return render(request, 'home/base.html')


@login_required
def special(request):
    return HttpResponse('you are logged in nice')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

    
def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'home/registration.html',
                                                    {'user_form':user_form,
                                                    'registered':registered,
                                                    'profile_form':profile_form})
        


#All the information related to login is here

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                print("account not active")

        else:
            Print("Invalid username and password")
            print("Username: {} Password: {}".format(username,password))
            return HttpResponse("invalid login details")

    else:
        return render(request, "home/login.html",{})
                



# Create your views here.
def others(request):
    return render(request, 'home/others.html')

templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-link" href="{% url 'index' %}">Index</a></li>
                <li><a class="navbar-link" href="{% url 'home:others' %}">Others</a></li>
                <li><a class="navbar-link" href="{% url 'home:register' %}">register</a></li>
            
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'home:user_login' %}">Login</a></li>
            {% endif %}
            </ul>                      
        </div>
    </nav>
    </div>    
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/home/index.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{% load static %}
{% block body_block %}
    <div class="container">
       <div class="jumbotron">
           <h1 id="bob">To Fill out the Form</h1>
            <h3>Visit formpage/</h3>
            <h3>{{ age|cut:'6' }}</h3>
            <h3>{{ name }}</h3>
       </div>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, blanditiis vitae doloribus id obcaecati vero fugit quos unde sint voluptatibus neque, harum molestias? Optio iure reiciendis quidem veritatis voluptate possimus!</p>
    </div>
{% endblock %}

templates/home/login.html
{% extends "home/base.html" %}
 {% load static %}
  {% block body_block %}
    <div class="container">
        <h1>Fill the form</h1><br>
        <form action="{% url 'home:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label for="password">Password:</label>
            <input type="password" name="password">

            <input class="btn btn-primary" type="submit" value="Login">
        </form>
        
    </div>
  {% endblock %}

templates/home/others.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/mystyle.css' %}">
    <title>Document</title>
</head>
<body>
    <h1 id='myHeader'>This is the other page</h1>
    <div class="container">
    <a href="{% url 'home:user' %}">users.html</a>
    <a href="{% url 'index' %}">sdssers.html</a>
    </div>
</body>
</html>

templates/home/registration.html
{% extends "home/base.html" %}
{% block body_block %}
   <div class="container">
    <div class="jumbotron">
        {% if registered %}
        <h1>Thank You for registerening</h1>
        {% else %}
        <h1>Fill Out The Form</h1>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="register">
        </form>
        {% endif %}
    </div>
   </div>
{% endblock %}